Major Rainloop update
- Backup/restore scripts
- Updated to YNH 2.4
- Fetch from source and integrity check
- Remove autoversion (not needed)
- Remove ynh_login_mapping (creates LDAP errors plus is it really
needed?). The plugin is still installed but not activated
- Domain hooks
- Backup before upgrade, restore if fail
- Remove disabled domains (users may want to add gmail addresses)
- Added auto-domain-grab plugin with wildcard domain. Users can try to
add aliases without admin config
- Add the admin password in config in case the password is lost

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,8 +1,18 @@
 #!/bin/bash
+	app=$YNH_APP_INSTANCE_NAME
+	rainloop_version='1.10.5.192'
 
-# Exit on command errors and treat unset variables as an error
-set -eu
-app=$YNH_APP_INSTANCE_NAME
+# Backup the current version of the app, restore it if the upgrade fails
+	sudo yunohost backup delete $app-before-upgrade
+	sudo yunohost backup create --apps $app --name $app-before-upgrade --quiet
+	EXIT_PROPERLY () {
+		trap '' EXIT
+		set +eu
+		sudo yunohost backup restore $app-before-upgrade --apps $app --force --quiet	# Restore the backup if upgrade failed
+		ynh_die "Upgrade failed. The app was restored to the way it was before the failed upgrade."
+	}
+	set -eu	
+	trap EXIT_PROPERLY ERR
 
 # Source app helpers
 . /usr/share/yunohost/helpers
@@ -18,30 +28,40 @@ app=$YNH_APP_INSTANCE_NAME
 	db_user=$app
 	plugins=$(ynh_app_setting_get "$app" plugins)
 
+# Correct path
+	if [ "${path:0:1}" != "/" ]; then
+		path="/$path"
+	fi
+	if [ "${path:${#path}-1}" == "/" ] && [ ${#path} -gt 1 ]; then
+		path="${path:0:${#path}-1}"
+	fi
+
 # no update for db now...
 
-# Create the final path and copy sources
+# Copy the new sources
 	final_path=/var/www/$app
 	rainloop_path=${final_path}/app
+	sudo rm -rf $rainloop_path/rainloop		# Remove the previous Rainloop files except data
 
-	# the old version is not deleted... the new version is in a new path
-
-	# Use of latest community edition
-	sudo wget -q https://github.com/RainLoop/rainloop-webmail/releases/download/v1.10.2.145/rainloop-community-1.10.2.145-74dc686dd82d9f29b0fef8ceb11c2903.zip
-	#Check checksum
-	sudo unzip -qq rainloop-community-1.10.2.*.zip -d $rainloop_path/
-
-	# Update patch to auto load version
-	sudo cp ../sources/patch/index_auto_version.php $rainloop_path/index.php
+	# Download sources and keys
+	sudo wget -q https://github.com/RainLoop/rainloop-webmail/releases/download/v${rainloop_version}/rainloop-community-${rainloop_version}.zip
+	sudo wget -q https://github.com/RainLoop/rainloop-webmail/releases/download/v${rainloop_version}/rainloop-community-${rainloop_version}.zip.asc
+	sudo wget -q https://repository.rainloop.net/RainLoop.asc
+	# Verify the integrity of sources	
+	sudo gpg --import --quiet RainLoop.asc
+	sudo gpg --verify --quiet rainloop-community-${rainloop_version}.zip.asc rainloop-community-${rainloop_version}.zip
+	sudo gpg --batch --delete-key --yes Rainloop
+	# Unzip and overwrite
+	sudo unzip -qq -o rainloop-community-${rainloop_version}.zip -d $rainloop_path/
 
 	# Update ynh plugins:
 	sudo mkdir -p $rainloop_path/data/_data_/_default_/plugins
+	sudo cp -rf ../sources/plugins/auto-domain-grab $rainloop_path/data/_data_/_default_/plugins/.
 	sudo cp -rf ../sources/plugins/ynh-login-mapping $rainloop_path/data/_data_/_default_/plugins/.
 	sudo cp -rf ../sources/plugins/ynh-ldap-suggestions $rainloop_path/data/_data_/_default_/plugins/.
 
-# update SSO and auto version
-	sudo cp ../sources/sso/sso.php                  $final_path/index.php
-	sudo cp ../sources/patch/index_auto_version.php $rainloop_path/index.php
+# update SSO
+	sudo cp ../sources/sso/sso.php        $final_path/index.php
 	sudo sed -i "s@domain.tld@$domain@g"  $final_path/index.php
 	sudo sed -i "s@PATHTOCHANGE@$path@g"  $final_path/index.php
 
